### ISSUE TITLE
Certificate on webauthn.org expired

### ISSUE THREAD

**Issue by daniel-e** [webauthn-open-source/fido2-server-demo#16]
When I open the webpage I get the error message:
"This server could not prove that it is webauthn.org; its security certificate expired 5 days ago."

Details of the certificate:
Issued On	Monday, September 17, 2018 at 8:46:24 PM
Expires On	Sunday, December 16, 2018 at 7:46:24 PM

**Comment by Teutone** [comment]
Expired again...
```
Web sites prove their identity via certificates, which are valid for a set time period. 

The certificate for webauthn.org expired on 16/06/2019.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

**Comment by ptman** [comment]
Please automate the cert renewal

**Comment by verglor** [comment]
Or just use cloudflare which handles it out of the box for free.

**Comment by JamesCullum** [comment]
The website is not maintained anymore
