### ISSUE TITLE
Failed on Android 7.0 with Firefox 68.3: Unknown reason

### ISSUE THREAD

**Issue by Sami32** [webauthn-open-source/fido2-server-demo#25]
U2F failed when i selected the fingerprint method.

And it didn't detected my Ledger Nano S U2F when selecting the USB method.

![Screenshot_2019-12-16-00-51-30-872_org mozilla firefox](https://user-images.githubusercontent.com/18471069/70871347-b62e4180-1f9e-11ea-8021-b61cc6af1ce3.jpg)

**Comment by JamesCullum** [comment]
Should be fixed in fido2-lib
